image: maven:3.9.4-eclipse-temurin-17

stages:
  - test

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Preparing environment..."
  - mvn -version

test_job:
  stage: test
  script:
    - mvn -e clean test -Dmaven.test.failure.ignore=true
  artifacts:
    when: always
    paths:
      - target/cucumber-reports/
      - target/allure-results/
      - target/site/allure-maven-plugin/
