image: maven:3.9.4-eclipse-temurin-17

stages:
  - test

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update && apt-get install -y firefox wget unzip xvfb
  - Xvfb :99 -ac &
  - export DISPLAY=:99
  - echo "Preparing environment..."
  - firefox --version
  - mvn -version

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn -B clean test
  artifacts:
    when: always
    paths:
      - target/cucumber-reports/
      - target/allure-results/
      - target/site/allure-maven-plugin/
