name: Run Automation Tests

# Triggers: when you push or make pull request to 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 using Eclipse Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache your Maven dependencies to speed up future builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Install Google Chrome on the GitHub runner
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 5: Run your Maven tests with headless browser
      - name: Run Tests
        run: |
          mvn clean test -DbrowserName=chrome -DuseWebdriverManager=true -DrunHeadless=true
